### ISSUE TITLE
no content

### ISSUE THREAD

**Issue by turbo-codes** [nahuelale/UniTube-UWP#1]
Hi,
I've tried to work on this project but nothing works:
Login fails
no content (videos)
menu doesn't work
Search doesn't work

Thanks

**Comment by nyx-lyb3ra** [comment]
Sorry, I forgot to add a README.md with compilation instructions when I uploaded the project to GitHub, I'll soon add one along with some commits I've been working on. 😉

**Comment by nahuelale** [comment]
Closed by #93a1ff4

**Comment by nyx-lyb3ra** [comment]
Check the new README.md if you want to build the project
