### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by davidmind** [nahuelale/UniTube-UWP#10]
Hi, @nahuelwexd am a graphics designer. I will like to know if you want me to create a logo for your project

**Comment by nyx-lyb3ra** [comment]
:thinking: Well... I already have a logo for UniTube, but if u want to propose something new and fresh, send it :smiley:

PS: This project is free and non profit

**Comment by davidmind** [comment]
Ok, i will go and work on my sketch and give you feed back

**Comment by davidmind** [comment]
@nahuelwexd 
After making my sketch this is what i came up with, if you like it i will proceed to make other file size. You can also make suggestion for the design.

![Unitube-presentaion-1.png](https://cdn.steemitimages.com/DQmYHyFQPhW7hX8AhuGfBUpqvNUQBfjr1ipSg97hjCangqA/Unitube-presentaion-1.png)

**Comment by nyx-lyb3ra** [comment]
@davidmind Hi, sorry for the delay in my response.
The logo that u made is very cool, I liked it a lot, but if u can make it red I think it will be better. We need to reference to YouTube, and YouTube is red, that's the reason.

**Comment by davidmind** [comment]
@nahuelwexd here is preview of the logo on YouTube red color. Should I make a pull request with other size or is there a need for further adjustment?
![Utube-1.png](https://cdn.steemitimages.com/DQmYDTnyUVtSKbWh92GH6iGCSzKfiWJMmBZiBRcujsb52rN/Utube-1.png)

**Comment by nyx-lyb3ra** [comment]
@davidmind I think it's good. Make the PR, I'll add it sooner

**Comment by davidmind** [comment]
hi, @nahuelwexd sorry i for the pull request is coming late. i was hooked up with somethings. [here](https://drive.google.com/open?id=1gOXpDQu0l4t-hCo5v5PyMDf4CLq0qJJW) is a link to all editable files

**Comment by davidmind** [comment]
@nahuelwexd are you there?

**Comment by davidmind** [comment]
@nahuelwexd are you there?

**Comment by nyx-lyb3ra** [comment]
@davidmind Hi, sorry, I was busy. I merged your PR

**Comment by davidmind** [comment]
Ok, nice to be part of your project contributor
